### ISSUE TITLE
Card payment Image not showing

### ISSUE THREAD

**Issue by hellotunmbi** [PaystackHQ/plugin-whmcs#7]
There is a link on modules/gateway/paystack.php file

The link: "https://paystack.com/assets/website/images/brand/badges/cards.png" on modules/gateway/paystack.php file gives an invalid URL.

This makes the pay with paystack icon on whmcs invoices not to show.

I have searched online for the correct current URL but found none.

**Comment by damilola-paystack** [comment]
This [PR](https://github.com/PaystackHQ/plugin-whmcs/pull/10) fixes the issue
